# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: 
    adapter: postgresql
    database: my_db
    pool: 5
    timeout: 5432

test: 
    adapter: postgresql
    database: my_db_test
    pool: 5
    timeout: 5432

production: 
    adapter: postgresql
    database: my_db_prod
    pool: 5
    timeout: 5432
